name: Test

on:  # yamllint disable-line rule:truthy
  push:
    branches:
      - develop
  pull_request:
    branches:
      - develop

  workflow_dispatch: ~

jobs:
  test:
    runs-on: ubuntu-latest
    container:
      image: ubuntu:latest
    steps:
      - uses: actions/checkout@v3
      - run: |
          echo ${{ github.workspace }}
          echo $GITHUB_WORKSPACE
          echo $(pwd)
